export const String = {
    appTitle: 'Textit',
    welcomeTitle: 'Connect mates easily & quickly',
    welcomeSubText: 'Our chat app is the perfect way to stay connected with friends and family.',
    or: 'OR',
    signupTitle: 'Sign up with mail',
    login: 'Login',
    signup: 'Sign up',
    exitingAccount: 'Exiting account?',
    loginTitle: 'Log in to Chatbox',
    loginSubText: 'Get chatting with friends and family today by signing up for our chat app!',
    emailLable: 'Your email',
    passwordLable: 'Password',
    confirmPasswordLable: 'Confirm password',
    userNameLable: 'Your name',
    email: 'email',
    password: 'password',
    confirmPassword: 'confirmPassword',
    username: 'userName',
    forgotPassword: 'Forgot password?',
    home: 'Home',
    searchUser: 'Search user',
    activeNow: 'Active now',
    you: 'You',
    noChat: 'No chat found',
    today: 'Today',
    yesterday: 'Yesterday',
    displayname: 'Display name',
    emailAddress: 'Email address',
    createGroup: 'Create group',
    dataNull: 'Data not found',
    typeMessage: 'Type a message',
    ok: 'Ok',
    cancel: 'Cancel',
    logout: 'Logout',

    logInSuccess: 'Log in successfully',
    emailRequired: 'Email is required',
    emailInvalid: 'Email is invalid',
    passwordRequired: 'Password is required',
    passwordInvalid: 'Password is too weak, please use a stronger password',
    confirmPasswordRequired: 'Confirm password is required',
    confirmPasswordInvalid: 'Password does not match',
    userNameRequired: 'User name is required',
    loginSuccess: 'Login success',
    loginFailed: 'Login failed',
    signupSuccess: 'Signup success',
    signupFailed: 'Signup failed',
    logoutSuccess: 'Logout success',
    logoutFailed: 'Logout failed',
    emailExitLogin: 'Email already exists. Please Take another email',
    weakPassword: 'password is too weak, please use a stronger password',
    userNotFound: 'User not found',
    invalidCredentials: 'Invalid credentials',
    logInFailed: 'Log in failed',
    logOutSuccess: 'Log out successfully',
    facebookLogin: 'Facebook login Successfully',
    appleLogin: 'Apple login Successfully',

    //provider
    google: 'Google',
    emailPassword: 'EmailPassword',

    //modal type and message
    alert: 'Alert',
    info: 'Info',
    backHandler: 'BackHandler',
    Ssuccess: 'Success',
    error: 'Error',
    backActionMessage: 'Are you sure you want to exit the app?',
    logoutMessage: 'Are you sure you want to logout?',
} as const;